"""Outcome-blind complete-system baselines outside the shared IsingFold action support.

The stock-minorminer adapter is optional and imported only inside an isolated worker.  Its
native search is compared as a complete system under a preregistered wall-clock/restart
budget; it is never inserted into the same-support causal ablations in :mod:`evaluate`.

The backend protocol is intentionally small enough for a future native OCT or ATOM adapter,
but only stock minorminer is registered.  Missing implementations are reported as missing;
this module never fabricates their outputs.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import multiprocessing
import operator
import os
import platform
import tempfile
import time
from dataclasses import dataclass, field, replace
from enum import Enum
from importlib import metadata as importlib_metadata
from pathlib import Path
from types import MappingProxyType
from typing import Hashable, Mapping, Protocol, Sequence

import networkx as nx

from isingfold.rl.contracts import Context, WorkVector, stable_digest
from isingfold.rl.env import EmbeddingTask, StrengthSelector
from isingfold.rl.evaluate import (
    INITIALIZATION_FAILURE,
    TASK_TERMINAL,
    EpisodeOutcome,
    EvaluationProtocolError,
    program_digest,
)
from isingfold.rl.evaluator import sample_program
from isingfold.rl.program import Program, program_features
from isingfold.rl.validate import p_embed, p_return

AUDIT_READS = 4_096
EXTERNAL_CONFIG_SCHEMA = "isingfold.external-baseline-config"
EXTERNAL_CONFIG_VERSION = 1
EXTERNAL_RECEIPT_SCHEMA = "isingfold.external-system-attempt"
EXTERNAL_RECEIPT_VERSION = 1
STOCK_MINORMINER_BACKEND = "stock-minorminer"
STOCK_MINORMINER_METHOD = "stock-minorminer-restarts-v1"
STOCK_MINORMINER_IMPLEMENTATION_PREFIX = (
    "native-package-persistent-subprocess-hard-deadline"
)
STOCK_MINORMINER_ARTIFACT_SCHEMA = "isingfold.stock-minorminer-artifact-manifest"
STOCK_MINORMINER_ARTIFACT_VERSION = 1

_STOCK_CODE_SUFFIXES = frozenset(
    {".c", ".cc", ".cpp", ".h", ".hpp", ".pxd", ".py", ".pyd", ".pyx", ".so", ".dylib", ".dll"}
)
_STOCK_METADATA_FILES = frozenset({"METADATA", "RECORD", "WHEEL"})


class ExternalBackendError(RuntimeError):
    """A backend/protocol fault, which must not be converted into a zero utility."""


class ExternalBackendStartupTimeout(TimeoutError):
    """The isolated publication worker could not start inside the total deadline."""


def stock_minorminer_artifact_manifest(*, expected_version: str) -> dict[str, object]:
    """Hash the installed stock-minorminer code and native artifacts.

    A distribution version alone is not an implementation identity: locally rebuilt wheels can
    retain the same version.  Generated bytecode and licenses are deliberately excluded, while
    Python/Cython/C/C++ sources, headers, native extensions, and wheel metadata are included.
    """

    distribution = importlib_metadata.distribution("minorminer")
    version = distribution.version
    if version != expected_version:
        raise ExternalBackendError(
            f"installed minorminer version {version!r} differs from registered "
            f"version {expected_version!r}"
        )
    files = distribution.files
    if files is None:
        raise ExternalBackendError("minorminer distribution exposes no installed-file registry")
    records: list[dict[str, object]] = []
    for entry in sorted(files, key=str):
        relative = Path(str(entry))
        if relative.is_absolute() or ".." in relative.parts:
            raise ExternalBackendError("minorminer distribution contains an unsafe file path")
        if relative.suffix.lower() not in _STOCK_CODE_SUFFIXES and relative.name not in (
            _STOCK_METADATA_FILES
        ):
            continue
        source = Path(distribution.locate_file(entry))
        if not source.is_file():
            raise ExternalBackendError(
                f"registered minorminer artifact is missing: {relative.as_posix()}"
            )
        content = source.read_bytes()
        records.append(
            {
                "path": relative.as_posix(),
                "sha256": hashlib.sha256(content).hexdigest(),
                "size_bytes": len(content),
            }
        )
    if not records or not any(
        Path(str(record["path"])).suffix.lower() in {".so", ".pyd", ".dylib", ".dll"}
        for record in records
    ):
        raise ExternalBackendError(
            "minorminer artifact registry does not contain its native extension"
        )
    payload: dict[str, object] = {
        "schema": STOCK_MINORMINER_ARTIFACT_SCHEMA,
        "schema_version": STOCK_MINORMINER_ARTIFACT_VERSION,
        "distribution": "minorminer",
        "distribution_version": version,
        "selection": "code-source-header-native-extension-and-wheel-metadata-v1",
        "files": records,
        "file_count": len(records),
    }
    return {**payload, "record_digest": stable_digest(payload)}


class SearchStatus(str, Enum):
    EMBEDDING = "EMBEDDING"
    NO_EMBEDDING = "NO_EMBEDDING"
    TIMED_OUT = "TIMED_OUT"
    ERROR = "ERROR"


@dataclass(frozen=True)
class BackendIdentity:
    """Versioned identity of one native external embedder implementation."""

    method_id: str
    distribution: str
    version: str
    entrypoint: str
    implementation: str

    def __post_init__(self) -> None:
        for name in self.__dataclass_fields__:
            value = getattr(self, name)
            if not isinstance(value, str) or not value:
                raise ValueError(f"backend identity {name} must be a nonempty string")

    def as_dict(self) -> dict[str, str]:
        return {name: getattr(self, name) for name in self.__dataclass_fields__}


@dataclass(frozen=True)
class BackendAvailability:
    available: bool
    reason: str
    identity: BackendIdentity | None = None

    def __post_init__(self) -> None:
        if type(self.available) is not bool or not self.reason:
            raise ValueError("backend availability needs a Boolean status and reason")
        if self.available != (self.identity is not None):
            raise ValueError("available backend must have an identity and unavailable one must not")

    def as_dict(self) -> dict[str, object]:
        return {
            "available": self.available,
            "reason": self.reason,
            "identity": None if self.identity is None else self.identity.as_dict(),
        }


@dataclass(frozen=True)
class BackendSearchResult:
    """One isolated native call, before independent IsingFold validation."""

    status: SearchStatus
    embedding: Mapping[Hashable, Sequence[Hashable]] | None
    elapsed_seconds: float = field(compare=False)
    detail: str = ""

    def __post_init__(self) -> None:
        object.__setattr__(self, "status", SearchStatus(self.status))
        if (
            isinstance(self.elapsed_seconds, bool)
            or not math.isfinite(self.elapsed_seconds)
            or self.elapsed_seconds < 0.0
        ):
            raise ValueError("backend elapsed time must be finite and nonnegative")
        if self.status is SearchStatus.EMBEDDING and self.embedding is None:
            raise ValueError("EMBEDDING status requires an embedding payload")
        if self.status is not SearchStatus.EMBEDDING and self.embedding is not None:
            raise ValueError("non-embedding status cannot carry an embedding payload")
        if not isinstance(self.detail, str):
            raise ValueError("backend result detail must be a string")


class ExternalEmbedderBackend(Protocol):
    """Plugin boundary for a real, independently versioned complete-system embedder."""

    identity: BackendIdentity

    def search(
        self,
        logical: nx.Graph,
        host: nx.Graph,
        *,
        seed: int,
        timeout_seconds: float,
        parameters: Mapping[str, int],
    ) -> BackendSearchResult: ...


@dataclass(frozen=True)
class ExternalBaselineConfig:
    """Preregistered stock-minorminer wall-clock, restart and information contract."""

    backend: str
    expected_backend_version: str
    embedding_wallclock_seconds: float
    max_restarts: int
    audit_reads: int
    selection_rule: str
    online_evaluator_feedback: bool
    minorminer_parameters: Mapping[str, int]

    _TOP_LEVEL_KEYS = frozenset(
        {
            "schema",
            "schema_version",
            "backend",
            "expected_backend_version",
            "embedding_wallclock_seconds",
            "max_restarts",
            "audit_reads",
            "selection_rule",
            "online_evaluator_feedback",
            "minorminer_parameters",
        }
    )
    _PARAMETER_KEYS = frozenset(
        {"tries", "threads", "max_no_improvement", "chainlength_patience"}
    )

    def __post_init__(self) -> None:
        if self.backend != STOCK_MINORMINER_BACKEND:
            raise ValueError(
                "only stock-minorminer is implemented; OCT and ATOM need native adapters"
            )
        if not isinstance(self.expected_backend_version, str) or not self.expected_backend_version:
            raise ValueError("expected backend version must be a nonempty string")
        if (
            isinstance(self.embedding_wallclock_seconds, bool)
            or not math.isfinite(self.embedding_wallclock_seconds)
            or self.embedding_wallclock_seconds <= 0.0
        ):
            raise ValueError("embedding wall-clock budget must be positive and finite")
        if (
            isinstance(self.max_restarts, bool)
            or not isinstance(self.max_restarts, int)
            or self.max_restarts <= 0
        ):
            raise ValueError("max_restarts must be a positive integer")
        if self.audit_reads != AUDIT_READS:
            raise ValueError("external publication evaluation fixes the final audit at 4096 reads")
        if self.selection_rule != "resource-lexicographic":
            raise ValueError("stock minorminer restarts use the registered resource-lexicographic rule")
        if self.online_evaluator_feedback is not False:
            raise ValueError("external baseline search cannot observe evaluator outcomes")
        parameters = dict(self.minorminer_parameters)
        if set(parameters) != self._PARAMETER_KEYS:
            raise ValueError("minorminer parameter registry has missing or unknown fields")
        if parameters["tries"] != 1:
            raise ValueError("each externally seeded restart must use minorminer tries=1")
        for name, value in parameters.items():
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError(f"minorminer parameter {name} must be a positive integer")
        object.__setattr__(self, "minorminer_parameters", MappingProxyType(parameters))

    @classmethod
    def from_mapping(cls, payload: Mapping[str, object]) -> ExternalBaselineConfig:
        if set(payload) != cls._TOP_LEVEL_KEYS:
            raise ValueError(
                "external baseline config schema differs: "
                f"missing={sorted(cls._TOP_LEVEL_KEYS - set(payload))}, "
                f"unknown={sorted(set(payload) - cls._TOP_LEVEL_KEYS)}"
            )
        if payload["schema"] != EXTERNAL_CONFIG_SCHEMA or payload["schema_version"] != 1:
            raise ValueError("unsupported external baseline config schema")
        parameters = payload["minorminer_parameters"]
        if not isinstance(parameters, Mapping):
            raise ValueError("minorminer_parameters must be an object")
        for name in (
            "backend",
            "expected_backend_version",
            "selection_rule",
        ):
            if not isinstance(payload[name], str):
                raise ValueError(f"external baseline config field {name} must be a string")
        return cls(
            backend=payload["backend"],
            expected_backend_version=payload["expected_backend_version"],
            embedding_wallclock_seconds=payload["embedding_wallclock_seconds"],
            max_restarts=payload["max_restarts"],
            audit_reads=payload["audit_reads"],
            selection_rule=payload["selection_rule"],
            online_evaluator_feedback=payload["online_evaluator_feedback"],
            minorminer_parameters=dict(parameters),
        )

    def as_dict(self) -> dict[str, object]:
        return {
            "schema": EXTERNAL_CONFIG_SCHEMA,
            "schema_version": EXTERNAL_CONFIG_VERSION,
            "backend": self.backend,
            "expected_backend_version": self.expected_backend_version,
            "embedding_wallclock_seconds": self.embedding_wallclock_seconds,
            "max_restarts": self.max_restarts,
            "audit_reads": self.audit_reads,
            "selection_rule": self.selection_rule,
            "online_evaluator_feedback": self.online_evaluator_feedback,
            "minorminer_parameters": dict(self.minorminer_parameters),
        }

    @property
    def digest(self) -> str:
        return stable_digest(self.as_dict())


def _stock_minorminer_worker(
    connection,
    logical: nx.Graph,
    host: nx.Graph,
    seed: int,
    internal_timeout: int,
    parameters: Mapping[str, int],
) -> None:
    """Child target: imports the optional native package and returns only its raw result."""

    try:
        import minorminer  # Optional dependency, deliberately isolated from normal imports.

        result = minorminer.find_embedding(
            logical,
            host,
            random_seed=seed,
            timeout=internal_timeout,
            return_overlap=False,
            verbose=0,
            interactive=False,
            **dict(parameters),
        )
        connection.send(("ok", result))
    except BaseException as exc:  # The parent turns this into an integrity error, never reward 0.
        connection.send(("error", type(exc).__name__, str(exc)))
    finally:
        connection.close()


def _stock_minorminer_persistent_worker(
    connection,
    logical: nx.Graph,
    host: nx.Graph,
    parameters: Mapping[str, int],
) -> None:
    """Import once, then serve all registered restarts for one task/repetition."""

    try:
        import minorminer  # Optional dependency, isolated from the parent process.

        connection.send(("ready",))
        while True:
            command = connection.recv()
            if command == ("stop",):
                return
            if (
                not isinstance(command, tuple)
                or len(command) != 3
                or command[0] != "search"
            ):
                connection.send(("error", "ProtocolError", "malformed search command"))
                return
            _, seed, internal_timeout = command
            try:
                result = minorminer.find_embedding(
                    logical,
                    host,
                    random_seed=seed,
                    timeout=internal_timeout,
                    return_overlap=False,
                    verbose=0,
                    interactive=False,
                    **dict(parameters),
                )
                connection.send(("ok", result))
            except BaseException as exc:
                connection.send(("error", type(exc).__name__, str(exc)))
                return
    except BaseException as exc:
        try:
            connection.send(("startup-error", type(exc).__name__, str(exc)))
        except (BrokenPipeError, EOFError, OSError):
            pass
    finally:
        connection.close()


class StockMinorminerSession:
    """One hard-deadline worker reused only within one sealed task/repetition."""

    def __init__(
        self,
        logical: nx.Graph,
        host: nx.Graph,
        *,
        parameters: Mapping[str, int],
        timeout_seconds: float,
    ) -> None:
        if not math.isfinite(timeout_seconds) or timeout_seconds <= 0.0:
            raise ValueError("persistent worker timeout must be positive and finite")
        started = time.perf_counter()
        context = multiprocessing.get_context("spawn")
        parent, child = context.Pipe(duplex=True)
        process = context.Process(
            target=_stock_minorminer_persistent_worker,
            args=(child, logical, host, dict(parameters)),
            daemon=True,
        )
        self._connection = parent
        self._process = process
        self._closed = False
        try:
            process.start()
            child.close()
            remaining = max(0.0, timeout_seconds - (time.perf_counter() - started))
            if remaining <= 0.0 or not parent.poll(remaining):
                self.close()
                raise ExternalBackendStartupTimeout(
                    "persistent minorminer worker exceeded the total online deadline"
                )
            payload = parent.recv()
            if payload != ("ready",):
                self.close()
                if isinstance(payload, tuple) and len(payload) == 3:
                    raise ExternalBackendError(
                        f"minorminer worker startup raised {payload[1]}: {payload[2]}"
                    )
                raise ExternalBackendError("minorminer worker startup response is malformed")
        except BaseException:
            if process.is_alive():
                _stop_process(process)
            parent.close()
            child.close()
            self._closed = True
            raise
        self.startup_seconds = time.perf_counter() - started

    def search(self, *, seed: int, timeout_seconds: float) -> BackendSearchResult:
        if self._closed or not self._process.is_alive():
            raise ExternalBackendError("persistent minorminer worker is not alive")
        if not 0 <= seed < 2**31:
            raise ValueError("minorminer seed must be a nonnegative 31-bit integer")
        if not math.isfinite(timeout_seconds) or timeout_seconds <= 0.0:
            raise ValueError("minorminer timeout must be positive and finite")
        started = time.perf_counter()
        self._connection.send(("search", seed, max(1, math.ceil(timeout_seconds))))
        remaining = max(0.0, timeout_seconds - (time.perf_counter() - started))
        if remaining <= 0.0 or not self._connection.poll(remaining):
            self.close()
            return BackendSearchResult(
                SearchStatus.TIMED_OUT,
                None,
                time.perf_counter() - started,
                "persistent external worker reached the registered restart deadline",
            )
        payload = self._connection.recv()
        elapsed = time.perf_counter() - started
        if not isinstance(payload, tuple) or not payload:
            raise ExternalBackendError("persistent minorminer worker returned malformed data")
        if payload[0] == "error" and len(payload) == 3:
            raise ExternalBackendError(
                f"minorminer worker raised {payload[1]}: {payload[2]}"
            )
        if payload[0] != "ok" or len(payload) != 2 or not isinstance(payload[1], dict):
            raise ExternalBackendError("persistent minorminer worker returned malformed data")
        if not payload[1]:
            return BackendSearchResult(SearchStatus.NO_EMBEDDING, None, elapsed)
        return BackendSearchResult(SearchStatus.EMBEDDING, payload[1], elapsed)

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self._process.is_alive():
            try:
                self._connection.send(("stop",))
            except (BrokenPipeError, EOFError, OSError):
                pass
            self._process.join(timeout=1.0)
        if self._process.is_alive():
            _stop_process(self._process)
        self._connection.close()

    def __enter__(self) -> StockMinorminerSession:
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        del exc_type, exc, traceback
        self.close()


class StockMinorminerBackend:
    """Native minorminer 0.2.22 behind a hard process-level deadline."""

    package_not_found_error = importlib_metadata.PackageNotFoundError

    def __init__(self, identity: BackendIdentity) -> None:
        self.identity = identity

    @classmethod
    def probe(cls, *, expected_version: str) -> BackendAvailability:
        try:
            artifact_manifest = stock_minorminer_artifact_manifest(
                expected_version=expected_version
            )
        except importlib_metadata.PackageNotFoundError:
            return BackendAvailability(
                False,
                "optional package unavailable; install with `python3 -m pip install -e '.[baseline]'`",
            )
        except ExternalBackendError as exc:
            return BackendAvailability(
                False,
                str(exc),
            )
        if importlib.util.find_spec("minorminer") is None:
            return BackendAvailability(False, "minorminer distribution exists but module is absent")
        version = str(artifact_manifest["distribution_version"])
        identity = BackendIdentity(
            method_id=STOCK_MINORMINER_METHOD,
            distribution="minorminer",
            version=version,
            entrypoint="minorminer.find_embedding",
            implementation=(
                f"{STOCK_MINORMINER_IMPLEMENTATION_PREFIX}:"
                f"artifact-record-sha256:{artifact_manifest['record_digest']}"
            ),
        )
        return BackendAvailability(True, "registered optional backend is available", identity)

    @classmethod
    def create(cls, *, expected_version: str) -> StockMinorminerBackend:
        availability = cls.probe(expected_version=expected_version)
        if not availability.available or availability.identity is None:
            raise ExternalBackendError(availability.reason)
        return cls(availability.identity)

    def open_session(
        self,
        logical: nx.Graph,
        host: nx.Graph,
        *,
        timeout_seconds: float,
        parameters: Mapping[str, int],
    ) -> StockMinorminerSession:
        """Start the one worker permitted for a sealed task/repetition."""

        return StockMinorminerSession(
            logical,
            host,
            parameters=parameters,
            timeout_seconds=timeout_seconds,
        )

    def search(
        self,
        logical: nx.Graph,
        host: nx.Graph,
        *,
        seed: int,
        timeout_seconds: float,
        parameters: Mapping[str, int],
    ) -> BackendSearchResult:
        if not 0 <= seed < 2**31:
            raise ValueError("minorminer seed must be a nonnegative 31-bit integer")
        if not math.isfinite(timeout_seconds) or timeout_seconds <= 0.0:
            raise ValueError("minorminer timeout must be positive and finite")
        started = time.perf_counter()
        context = multiprocessing.get_context("spawn")
        receiver, sender = context.Pipe(duplex=False)
        process = context.Process(
            target=_stock_minorminer_worker,
            args=(
                sender,
                logical,
                host,
                seed,
                max(1, math.ceil(timeout_seconds)),
                dict(parameters),
            ),
            daemon=True,
        )
        process_started = False
        try:
            process.start()
            process_started = True
            sender.close()
            remaining = max(0.0, timeout_seconds - (time.perf_counter() - started))
            if remaining <= 0.0 or not receiver.poll(remaining):
                _stop_process(process)
                return BackendSearchResult(
                    SearchStatus.TIMED_OUT,
                    None,
                    time.perf_counter() - started,
                    "external supervisor reached the registered restart deadline",
                )
            payload = receiver.recv()
            process.join(timeout=max(0.0, timeout_seconds - (time.perf_counter() - started)))
            if process.is_alive():
                _stop_process(process)
            if not isinstance(payload, tuple) or not payload:
                raise ExternalBackendError("minorminer worker returned a malformed payload")
            if payload[0] == "error" and len(payload) == 3:
                raise ExternalBackendError(
                    f"minorminer worker raised {payload[1]}: {payload[2]}"
                )
            if payload[0] != "ok" or len(payload) != 2 or not isinstance(payload[1], dict):
                raise ExternalBackendError("minorminer worker returned a malformed result")
            embedding = payload[1]
            elapsed = time.perf_counter() - started
            if not embedding:
                return BackendSearchResult(SearchStatus.NO_EMBEDDING, None, elapsed)
            return BackendSearchResult(SearchStatus.EMBEDDING, embedding, elapsed)
        finally:
            receiver.close()
            if process_started and process.is_alive():
                _stop_process(process)


def _stop_process(process: multiprocessing.Process) -> None:
    process.terminate()
    process.join(timeout=1.0)
    if process.is_alive():
        process.kill()
        process.join(timeout=1.0)


@dataclass(frozen=True)
class RestartReceipt:
    restart_index: int
    seed: int
    status: str
    elapsed_seconds: float = field(compare=False)
    embedding_digest: str | None = None
    validation_digest: str | None = None
    qubits: int | None = None
    max_chain: int | None = None
    detail: str = ""

    def __post_init__(self) -> None:
        if self.status not in {
            "VALID_CANDIDATE",
            "INVALID_CANDIDATE",
            SearchStatus.NO_EMBEDDING.value,
            SearchStatus.TIMED_OUT.value,
        }:
            raise ValueError(f"unknown restart status {self.status!r}")
        if self.restart_index < 0 or not 0 <= self.seed < 2**31:
            raise ValueError("restart index/seed is outside its domain")
        if not math.isfinite(self.elapsed_seconds) or self.elapsed_seconds < 0.0:
            raise ValueError("restart elapsed time must be finite and nonnegative")

    def as_dict(self) -> dict[str, object]:
        return {
            "restart_index": self.restart_index,
            "seed": self.seed,
            "status": self.status,
            "elapsed_seconds": self.elapsed_seconds,
            "embedding_digest": self.embedding_digest,
            "validation_digest": self.validation_digest,
            "qubits": self.qubits,
            "max_chain": self.max_chain,
            "detail": self.detail,
        }


@dataclass(frozen=True)
class ExternalAttemptReceipt:
    instance: str
    lineage: str
    repetition: int
    system_seed: int
    evaluator_seed: int
    backend: BackendIdentity
    config_digest: str
    restarts: tuple[RestartReceipt, ...]
    selected_restart: int | None
    selection_rule: str
    online_evaluator_feedback: bool
    returned_valid: bool
    validation_digest: str
    program_digest: str | None
    selected_strength_index: int | None
    selected_strength: float | None
    evaluator_hits: int | None
    evaluator_reads: int | None
    work: WorkVector
    embedding_phase_seconds: float = field(compare=False)
    postprocessing_seconds: float = field(compare=False)
    online_seconds: float = field(compare=False)
    evaluator_seconds: float | None = field(default=None, compare=False)

    def __post_init__(self) -> None:
        if not self.instance or not self.lineage:
            raise ValueError("external receipt needs nonempty instance and lineage identifiers")
        if self.repetition < 0 or not 0 <= self.system_seed < 2**31:
            raise ValueError("external repetition/system seed is outside its domain")
        if not 0 <= self.evaluator_seed < 2**31:
            raise ValueError("external evaluator seed is outside its domain")
        if len(self.config_digest) != 64 or len(self.validation_digest) != 64:
            raise ValueError("external receipt is missing a SHA-256 config/validation digest")
        if not self.restarts:
            raise ValueError("external receipt must retain every invoked restart")
        indices = tuple(item.restart_index for item in self.restarts)
        if indices != tuple(range(len(self.restarts))):
            raise ValueError("external restart indices must be contiguous from zero")
        if len(self.restart_seeds) != len(set(self.restart_seeds)):
            raise ValueError("external restart seeds must be distinct inside one attempt")
        if self.selection_rule != "resource-lexicographic":
            raise ValueError("external receipt has an unregistered candidate selection rule")
        if self.online_evaluator_feedback is not False:
            raise ValueError("external search receipt cannot claim evaluator feedback")
        for name in ("embedding_phase_seconds", "postprocessing_seconds", "online_seconds"):
            value = getattr(self, name)
            if not math.isfinite(value) or value < 0.0:
                raise ValueError(f"external {name} must be finite and nonnegative")
        if not math.isclose(
            self.embedding_phase_seconds + self.postprocessing_seconds,
            self.online_seconds,
            rel_tol=0.0,
            abs_tol=1e-9,
        ):
            raise ValueError("external online time does not equal embedding plus postprocessing")
        if self.work.restart_work != len(self.restarts):
            raise ValueError("external work receipt omits one or more native restarts")
        valid_indices = {
            item.restart_index for item in self.restarts if item.status == "VALID_CANDIDATE"
        }
        if self.returned_valid:
            if self.selected_restart not in valid_indices:
                raise ValueError("external valid return does not select a validated restart")
            if (
                self.program_digest is None
                or len(self.program_digest) != 64
                or self.selected_strength_index not in range(4)
                or self.selected_strength is None
                or not math.isfinite(self.selected_strength)
                or self.selected_strength <= 0.0
                or self.evaluator_hits is None
                or self.evaluator_reads != AUDIT_READS
                or not 0 <= self.evaluator_hits <= self.evaluator_reads
                or self.work.compiler_calls != 4
                or self.work.evaluator_reads != AUDIT_READS
                or self.evaluator_seconds is None
                or not math.isfinite(self.evaluator_seconds)
                or self.evaluator_seconds < 0.0
            ):
                raise ValueError("external valid return has incomplete program/evaluator provenance")
        elif any(
            value is not None
            for value in (
                self.selected_restart,
                self.program_digest,
                self.selected_strength_index,
                self.selected_strength,
                self.evaluator_hits,
                self.evaluator_reads,
                self.evaluator_seconds,
            )
        ):
            raise ValueError("external no-valid return cannot claim a selected/evaluated program")

    @property
    def restart_seeds(self) -> tuple[int, ...]:
        return tuple(item.seed for item in self.restarts)

    def as_dict(self, *, include_digest: bool = True) -> dict[str, object]:
        payload: dict[str, object] = {
            "schema": EXTERNAL_RECEIPT_SCHEMA,
            "schema_version": EXTERNAL_RECEIPT_VERSION,
            "instance": self.instance,
            "lineage": self.lineage,
            "repetition": self.repetition,
            "system_seed": self.system_seed,
            "evaluator_seed": self.evaluator_seed,
            "backend": self.backend.as_dict(),
            "config_digest": self.config_digest,
            "restarts": [item.as_dict() for item in self.restarts],
            "selected_restart": self.selected_restart,
            "selection_rule": self.selection_rule,
            "online_evaluator_feedback": self.online_evaluator_feedback,
            "returned_valid": self.returned_valid,
            "validation_digest": self.validation_digest,
            "program_digest": self.program_digest,
            "selected_strength_index": self.selected_strength_index,
            "selected_strength": self.selected_strength,
            "evaluator_hits": self.evaluator_hits,
            "evaluator_reads": self.evaluator_reads,
            "work": self.work.as_dict(),
            "embedding_phase_seconds": self.embedding_phase_seconds,
            "postprocessing_seconds": self.postprocessing_seconds,
            "online_seconds": self.online_seconds,
            "evaluator_seconds": self.evaluator_seconds,
        }
        if include_digest:
            payload["record_digest"] = stable_digest(payload)
        return payload


def _seed(base_seed: int, domain: str, task: EmbeddingTask, repetition: int) -> int:
    payload = {
        "base_seed": base_seed,
        "domain": domain,
        "instance": task.name,
        "lineage": task.lineage or task.name,
        "repetition": repetition,
    }
    return int.from_bytes(
        hashlib.sha256(
            json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        ).digest()[:4],
        "big",
    ) % (2**31)


def _restart_seed(system_seed: int, method_id: str, restart_index: int) -> int:
    return int.from_bytes(
        hashlib.sha256(f"{system_seed}:{method_id}:{restart_index}".encode()).digest()[:4],
        "big",
    ) % (2**31)


def _embedding_digest(chains: Mapping[Hashable, frozenset[Hashable]]) -> str:
    rows = sorted(
        (
            f"{type(owner).__module__}.{type(owner).__qualname__}:{owner!r}",
            sorted(
                f"{type(qubit).__module__}.{type(qubit).__qualname__}:{qubit!r}"
                for qubit in chain
            ),
        )
        for owner, chain in chains.items()
    )
    return stable_digest({"domain": "isingfold-external-embedding-v1", "chains": rows})


def _normalise_embedding(
    raw: Mapping[Hashable, Sequence[Hashable]],
) -> dict[Hashable, frozenset[Hashable]]:
    if not isinstance(raw, Mapping):
        raise ExternalBackendError("external backend embedding is not a mapping")
    try:
        return {owner: frozenset(chain) for owner, chain in raw.items()}
    except (TypeError, ValueError) as exc:
        raise ExternalBackendError("external backend returned malformed branch sets") from exc


def _select_strength(
    selector: StrengthSelector,
    ctx: Context,
    task: EmbeddingTask,
    chains: Mapping[Hashable, frozenset[Hashable]],
    programs: Sequence[Program],
) -> int:
    features = [program_features(program, chains, task.problem) for program in programs]
    if all(
        hasattr(selector, name)
        for name in (
            "select_embedding",
            "deployment_ready",
            "normalizer_digest",
            "coefficient_transform_scale",
        )
    ):
        graph_selector = selector
        if not graph_selector.deployment_ready:
            raise ExternalBackendError("external evaluation selector is not deployment-ready")
        from isingfold.rl.strength_tensorize import build_strength_inputs

        inputs = build_strength_inputs(
            ctx=ctx,
            logical=task.logical,
            host=task.host,
            problem=task.problem,
            chains=chains,
            programs=programs,
            coef_scale=float(graph_selector.coefficient_transform_scale),
            normalizer_digest=graph_selector.normalizer_digest,
        )
        raw = graph_selector.select_embedding(inputs)
    else:
        raw = selector(programs, features)
    try:
        index = operator.index(raw)
    except TypeError as exc:
        raise ExternalBackendError("strength selector returned a non-integral index") from exc
    if not 0 <= index < len(programs):
        raise ExternalBackendError("strength selector returned an out-of-range index")
    return index


def run_external_system(
    tasks: Sequence[EmbeddingTask],
    ctx: Context,
    backend: ExternalEmbedderBackend,
    config: ExternalBaselineConfig,
    *,
    selector: StrengthSelector,
    seed: int = 0,
    repetitions: int = 1,
) -> tuple[list[EpisodeOutcome], list[ExternalAttemptReceipt]]:
    """Run outcome-blind independent restarts and one fresh final audit per valid return."""

    if isinstance(seed, bool) or not isinstance(seed, int) or seed < 0:
        raise ValueError("seed must be a nonnegative integer")
    if isinstance(repetitions, bool) or not isinstance(repetitions, int) or repetitions <= 0:
        raise ValueError("repetitions must be a positive integer")
    if config.audit_reads != ctx.audit_reads or config.audit_reads > ctx.caps.evaluator_reads:
        raise ValueError("external audit reads must equal the registered context audit block")
    identities = [(task.lineage or task.name, task.name) for task in tasks]
    if len(identities) != len(set(identities)):
        raise ValueError("external evaluation population contains duplicate instance identities")
    for task in tasks:
        if task.ground_energy is None or not math.isfinite(task.ground_energy):
            raise ValueError(f"external IF-Q3 evaluation needs a finite target for {task.name!r}")

    outcomes: list[EpisodeOutcome] = []
    detailed: list[ExternalAttemptReceipt] = []
    for repetition in range(repetitions):
        for task in tasks:
            system_seed = _seed(seed, "policy", task, repetition)
            evaluator_seed = _seed(seed, "final-evaluator", task, repetition)
            started = time.perf_counter()
            restart_receipts: list[RestartReceipt] = []
            candidates: list[
                tuple[int, dict[Hashable, frozenset[Hashable]], int, int, str]
            ] = []
            validator_calls = 0
            for restart_index in range(config.max_restarts):
                remaining = config.embedding_wallclock_seconds - (time.perf_counter() - started)
                if remaining <= 0.0:
                    break
                restart_seed = _restart_seed(
                    system_seed,
                    backend.identity.method_id,
                    restart_index,
                )
                result = backend.search(
                    task.logical,
                    task.host,
                    seed=restart_seed,
                    timeout_seconds=remaining,
                    parameters=config.minorminer_parameters,
                )
                if result.status is SearchStatus.ERROR:
                    raise ExternalBackendError(result.detail or "external backend error")
                if result.status is not SearchStatus.EMBEDDING:
                    restart_receipts.append(
                        RestartReceipt(
                            restart_index,
                            restart_seed,
                            result.status.value,
                            result.elapsed_seconds,
                            detail=result.detail,
                        )
                    )
                    continue

                assert result.embedding is not None
                chains = _normalise_embedding(result.embedding)
                receipt = p_embed(chains, task.logical, task.host, ctx.qubit_cap)
                validator_calls += 1
                embedding_digest = _embedding_digest(chains)
                validation_digest = stable_digest(receipt.as_dict())
                status = "VALID_CANDIDATE" if receipt.valid else "INVALID_CANDIDATE"
                restart_receipts.append(
                    RestartReceipt(
                        restart_index,
                        restart_seed,
                        status,
                        result.elapsed_seconds,
                        embedding_digest,
                        validation_digest,
                        receipt.qubits,
                        receipt.max_chain,
                        "; ".join(receipt.reasons),
                    )
                )
                if receipt.valid:
                    candidates.append(
                        (
                            restart_index,
                            chains,
                            receipt.qubits,
                            receipt.max_chain,
                            embedding_digest,
                        )
                    )

            embedding_phase_seconds = time.perf_counter() - started
            online_seconds = embedding_phase_seconds
            base_work = WorkVector(
                restart_work=len(restart_receipts),
                validator_calls=validator_calls,
            )
            if not candidates:
                validation_digest = stable_digest(
                    {
                        "kind": "EXTERNAL_NO_VALID_EMBEDDING",
                        "restarts": [item.as_dict() for item in restart_receipts],
                    }
                )
                outcome = EpisodeOutcome(
                    instance=task.name,
                    lineage=task.lineage or task.name,
                    returned_valid=False,
                    utility=0.0,
                    qubits=None,
                    max_chain=None,
                    decisions=0,
                    selected_strength=None,
                    reason="EXTERNAL_NO_VALID_EMBEDDING",
                    repetition=repetition,
                    episode_seed=system_seed,
                    work=base_work,
                    validation_digest=validation_digest,
                    online_seconds=online_seconds,
                )
                outcome.validate_receipt(require_complete=True)
                detail = ExternalAttemptReceipt(
                    instance=task.name,
                    lineage=task.lineage or task.name,
                    repetition=repetition,
                    system_seed=system_seed,
                    evaluator_seed=evaluator_seed,
                    backend=backend.identity,
                    config_digest=config.digest,
                    restarts=tuple(restart_receipts),
                    selected_restart=None,
                    selection_rule=config.selection_rule,
                    online_evaluator_feedback=False,
                    returned_valid=False,
                    validation_digest=validation_digest,
                    program_digest=None,
                    selected_strength_index=None,
                    selected_strength=None,
                    evaluator_hits=None,
                    evaluator_reads=None,
                    work=base_work,
                    embedding_phase_seconds=embedding_phase_seconds,
                    postprocessing_seconds=0.0,
                    online_seconds=online_seconds,
                )
                outcomes.append(outcome)
                detailed.append(detail)
                continue

            selected_restart, chains, _, _, _ = min(
                candidates,
                key=lambda item: (item[2], item[3], item[4], item[0]),
            )
            final_validation, programs = p_return(
                chains,
                task.logical,
                task.host,
                task.problem,
                ctx,
            )
            validator_calls += 1
            if not final_validation.valid or len(programs) != 4:
                raise ExternalBackendError(
                    "resource-selected embedding failed independent return validation"
                )
            selected_strength_index = _select_strength(selector, ctx, task, chains, programs)
            selected_program = programs[selected_strength_index]
            online_seconds = time.perf_counter() - started
            postprocessing_seconds = max(0.0, online_seconds - embedding_phase_seconds)
            evaluator_started = time.perf_counter()
            block = sample_program(
                selected_program,
                chains,
                task.problem,
                task.ground_energy,
                num_reads=config.audit_reads,
                seed=evaluator_seed,
                num_sweeps=ctx.num_sweeps,
            )
            evaluator_seconds = time.perf_counter() - evaluator_started
            if block.strength_index != selected_strength_index or block.reads != config.audit_reads:
                raise ExternalBackendError("external evaluator returned the wrong program/read block")
            total_work = WorkVector(
                restart_work=len(restart_receipts),
                validator_calls=validator_calls,
                compiler_calls=4,
                evaluator_reads=block.reads,
                feature_work=4,
            )
            digest = program_digest(selected_program, chains)
            validation_digest = stable_digest(final_validation.as_dict())
            outcome = EpisodeOutcome(
                instance=task.name,
                lineage=task.lineage or task.name,
                returned_valid=True,
                utility=block.rate,
                qubits=final_validation.qubits,
                max_chain=final_validation.max_chain,
                decisions=0,
                selected_strength=selected_program.strength,
                reason="EXTERNAL_VALID_RETURN",
                repetition=repetition,
                episode_seed=system_seed,
                evaluator_seed=evaluator_seed,
                program_digest=digest,
                selected_strength_index=selected_strength_index,
                evaluator_hits=block.hits,
                evaluator_reads=block.reads,
                work=total_work,
                validation_digest=validation_digest,
                broken_chain_fraction=block.broken_fraction,
                mean_energy_residual=block.mean_residual,
                online_seconds=online_seconds,
                evaluator_seconds=evaluator_seconds,
            )
            outcome.validate_receipt(require_complete=True)
            detail = ExternalAttemptReceipt(
                instance=task.name,
                lineage=task.lineage or task.name,
                repetition=repetition,
                system_seed=system_seed,
                evaluator_seed=evaluator_seed,
                backend=backend.identity,
                config_digest=config.digest,
                restarts=tuple(restart_receipts),
                selected_restart=selected_restart,
                selection_rule=config.selection_rule,
                online_evaluator_feedback=False,
                returned_valid=True,
                validation_digest=validation_digest,
                program_digest=digest,
                selected_strength_index=selected_strength_index,
                selected_strength=selected_program.strength,
                evaluator_hits=block.hits,
                evaluator_reads=block.reads,
                work=total_work,
                embedding_phase_seconds=embedding_phase_seconds,
                postprocessing_seconds=postprocessing_seconds,
                online_seconds=online_seconds,
                evaluator_seconds=evaluator_seconds,
            )
            outcomes.append(outcome)
            detailed.append(detail)
    return outcomes, detailed


def external_method_metadata(
    config: ExternalBaselineConfig,
    identity: BackendIdentity,
) -> dict[str, object]:
    """Paper-facing information and comparison boundary for the external arm."""

    return {
        "method_id": identity.method_id,
        "backend": identity.as_dict(),
        "comparison_scope": "external-complete-system",
        "same_support_causal_ablation": False,
        "selection_rule": config.selection_rule,
        "restart_rule": "independent-seeded-native-calls-until-cap-or-wallclock",
        "hard_timeout": "process-level-supervisor-per-native-call",
        "embedding_wallclock_seconds": config.embedding_wallclock_seconds,
        "max_restarts": config.max_restarts,
        "minorminer_parameters": dict(config.minorminer_parameters),
        "online_evaluator_feedback": False,
        "evaluator_oracle": False,
        "controller_timing_scope": (
            "not-applicable; native search and postprocessing are timed by the external "
            "complete-system receipt"
        ),
        "final_evaluator": "one-fresh-independent-4096-read-block-after-selection",
        "native_operation_counters": "unavailable-from-public-api",
        "work_counter_semantics": {
            "restart_work": "number-of-invoked-native-minorminer-calls",
            "validator_calls": "independent-candidate-screens-plus-final-revalidation",
            "compiler_calls": "four-program-registry-for-selected-valid-return",
            "evaluator_reads": "fresh-final-read-block-for-valid-return",
            "route_expansions": "unavailable-not-comparable-zero-placeholder",
            "materializations": "unavailable-not-comparable-zero-placeholder",
            "cut_edge_visits": "unavailable-not-comparable-zero-placeholder",
        },
        "unimplemented_plugin_slots": ["OCT", "ATOM"],
        "python_version": platform.python_version(),
        "networkx_version": importlib_metadata.version("networkx"),
        "dimod_version": importlib_metadata.version("dimod"),
        "dwave_samplers_version": importlib_metadata.version("dwave-samplers"),
    }


def unconditional_system_outcomes(
    outcomes: Sequence[EpisodeOutcome],
) -> list[EpisodeOutcome]:
    """Convert Profile-I initializer failures to complete-system utility-zero attempts.

    Policy-learning analyses keep initializer failures outside the conditional episode
    population.  An external whole-system comparison has a different estimand: every sealed
    task/repetition attempt counts, so failure to initialize is exactly utility zero.  This
    explicit conversion prevents the conditional and unconditional estimands from being
    silently mixed.
    """

    converted: list[EpisodeOutcome] = []
    for outcome in outcomes:
        outcome.validate_receipt(require_complete=True)
        if outcome.outcome_kind == INITIALIZATION_FAILURE:
            unconditional = replace(
                outcome,
                utility=0.0,
                reason=f"INITIALIZATION_FAILURE_ZERO:{outcome.reason}",
                outcome_kind=TASK_TERMINAL,
                population_eligible=True,
            )
            unconditional.validate_receipt(require_complete=True)
            converted.append(unconditional)
        else:
            converted.append(outcome)
    return converted


def write_external_attempt_receipts(
    path: str | os.PathLike[str],
    receipts: Sequence[ExternalAttemptReceipt],
    *,
    overwrite: bool = False,
) -> str:
    """Atomically write canonical detailed JSONL and return its file SHA-256."""

    if not receipts:
        raise EvaluationProtocolError("cannot write an empty external receipt batch")
    keys = [(item.lineage, item.instance, item.repetition) for item in receipts]
    if len(keys) != len(set(keys)):
        raise EvaluationProtocolError("external receipt batch contains duplicate pair keys")
    rows = sorted(receipts, key=lambda item: (item.lineage, item.instance, item.repetition))
    content = b"".join(
        (
            json.dumps(
                item.as_dict(),
                sort_keys=True,
                separators=(",", ":"),
                allow_nan=False,
            )
            + "\n"
        ).encode("utf-8")
        for item in rows
    )
    digest = hashlib.sha256(content).hexdigest()
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and not overwrite:
        raise FileExistsError(destination)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if overwrite:
            os.replace(temporary, destination)
        else:
            try:
                os.link(temporary, destination)
            except FileExistsError:
                raise FileExistsError(destination) from None
            temporary.unlink()
    finally:
        temporary.unlink(missing_ok=True)
    return digest


__all__ = [
    "AUDIT_READS",
    "BackendAvailability",
    "BackendIdentity",
    "BackendSearchResult",
    "ExternalAttemptReceipt",
    "ExternalBackendError",
    "ExternalBackendStartupTimeout",
    "ExternalBaselineConfig",
    "ExternalEmbedderBackend",
    "RestartReceipt",
    "SearchStatus",
    "StockMinorminerBackend",
    "StockMinorminerSession",
    "external_method_metadata",
    "run_external_system",
    "unconditional_system_outcomes",
    "write_external_attempt_receipts",
]
