# End to end on this tree, small enough to finish while we watch it. Nothing here reads the old
# working copy: ISINGFOLD_SRC points at this checkout and the editable finder is stripped inside
# every entry point.
set -eu
cd ~/prj_IsingFold
source ~/isingfold/.venv/bin/activate
export ISINGFOLD_SRC=$HOME/prj_IsingFold/src
export PYTHONPATH=$ISINGFOLD_SRC
export OMP_NUM_THREADS=2
mkdir -p runs
say () { printf "\n=== %s\n" "$1"; }

say "1. corpus, generated by this tree, seed recorded"
python -u probes/gen_corpus.py --out runs/smoke_corpus --host chimera --host-size 4 \
  --variables 16 --chain-size 3 --fault-rate 0.0 --qubit-cap 120 --instances 60 \
  --alpha 0.9 --weights 0.4,1.0,2.5 --clause-length 5 --seed 20260914 2>&1 | tail -3
python - <<'PY'
import json
m = json.load(open("runs/smoke_corpus/manifest.json"))
print("corpus digest", m["digest"], "instances", m["instances"], "split", m["split"])
PY

say "2. train, this tree's own trainer, the new quality head active"
python -u probes/train_bestof.py --corpus runs/smoke_corpus --family if-core \
  --out runs/smoke_bestof --initializer minorminer --rounds 3 --window 10 --lineages 8 --k 6 \
  --epochs 1 --eval-every 1 --eval-instances 12 --seed 0 2>&1 | tail -4

say "3. measure, selection and assessment separated"
python -u probes/frontier2.py --corpus runs/smoke_corpus --split test --lineages 10 \
  --ladder 2,4,8 --rounds 1,2 --draws 8 \
  --checkpoints if-core=runs/smoke_bestof/policy.pt 2>&1 | tail -22
echo "SMOKE DONE"
