# The first full run executed from the published tree rather than from a working copy. Three
# things differ from every earlier run, and only the third is a change of method.
#
#   * the source is this checkout, pinned through ISINGFOLD_SRC, and the corpus is generated by
#     it from a seed recorded here, so the command in this file reproduces the digest;
#   * the model carries the per-action quality head this tree added, which the older checkpoints
#     do not have: loading one of them here leaves six tensors uninitialised, so nothing is
#     resumed and every family trains from scratch;
#   * the episode is protected by stock minorminer, so the policy learns to improve on the
#     standard tool rather than to replace it.
set -eu
cd ~/prj_IsingFold
source ~/isingfold/.venv/bin/activate
export ISINGFOLD_SRC=$HOME/prj_IsingFold/src
export PYTHONPATH=$ISINGFOLD_SRC
export OMP_NUM_THREADS=3
mkdir -p runs/v1

CORPUS=runs/v1/corpus
if [ ! -s "$CORPUS/manifest.json" ]; then
  python -u probes/gen_corpus.py --out "$CORPUS" --host chimera --host-size 4 \
    --variables 16 --chain-size 3 --fault-rate 0.0 --qubit-cap 120 --instances 600 \
    --alpha 0.9 --weights 0.4,1.0,2.5 --clause-length 5 --seed 20260914 \
    > runs/v1/corpus.log 2>&1
fi
python - <<'PY' >> runs/v1/corpus.log
import json
m = json.load(open("runs/v1/corpus/manifest.json"))
print("CORPUS digest", m["digest"], "instances", m["instances"], "split", m["split"])
PY
tail -1 runs/v1/corpus.log

for F in if-core if-dual if-mlp; do
  LOG=runs/v1/train_${F}.log
  [ -s "$LOG" ] && { echo "skip $F, $LOG is not empty"; continue; }
  python -u probes/train_bestof.py --corpus "$CORPUS" --family $F --out runs/v1/bestof_$F \
    --initializer minorminer --mm-tries 10 --rounds 60 --window 10 --lineages 24 --k 8 \
    --epochs 2 --learning-rate 3e-4 --seed 0 --eval-every 5 --eval-instances 40 \
    > "$LOG" 2>&1 &
  sleep 5
done
wait
echo "V1 TRAINING DONE"
